[tool.poetry]
name = "btc2sim"
version = "0.0.2"
description = ""
authors = ["Noah Syrkis <noah@syrkis.com>"]
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
venvPath = "."
venv = ".venv"
